# Author -- meevs
# Creation Date -- 2023-07-10
# File Name -- compose.yaml
# Notes --

version: "2.4"
services:
  latest:
    container_name: "spigot_mc-${MC_VERSION}"
    image: "spigot_mc-${MC_VERSION}-img"
    build:
      context: "./"
      args:
        INSTALL_DIR: "${INSTALL_DIR}"
        JAVA_VERSION: "${JAVA_VERSION}"
        MC_VERSION: "${MC_VERSION}"
        SERVER_CONFIG: "${SERVER_CONFIG}"
        MC_EULA: "${MC_EULA}"
    environment:
      MIN_RAM: "2G"
      MAX_RAM: "4G"
    stdin_open: "true"
    tty: "true"
    ports:
      - "25565:25565/tcp"
    volumes:
      - type: "volume"
        source: "data"
        target: "${INSTALL_DIR}"

volumes:
  data: {}
